apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: group-du-sno-policies-generator
placementBindingDefaults:
  name: group-du-sno-policies-placement-binding
policyDefaults:
  # categories: []
  #controls:
  #  - PR.DS-1 Data-at-rest
  namespace: group-du-sno-policies
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    clusterSelectors:
      group-du-sno: ""
  remediationAction: enforce
  severity: medium
  # standards: []
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
policies:
  # Create group-du-sno policies
- name: console-policy
  manifests:
    - path: source-crs/ConsoleOperatorDisable.yaml
- name: log-forwarder-policy
  manifests:
    - path: source-crs/ClusterLogForwarder.yaml
      patches:
        - spec:
            outputs:
              - type: "kafka"
                name: kafka-open
               # below url is an example
                url: "tcp://10.46.55.190:9092/test"
            pipelines:
              - name: audit-logs
                inputRefs:
                - audit
                outputRefs:
                - kafka-open
              - name: infrastructure-logs
                inputRefs:
                - infrastructure
                outputRefs:
                - kafka-open
- name: "log-policy"
  manifests:
    - path: source-crs/ClusterLogging.yaml
      patches:
        - spec:
            curation:
              curator:
                schedule: "30 3 * * *"
            collection:
              logs:
                type: "fluentd"
                fluentd: {}
- name: mc-sctp-policy
  manifests:
    - path: source-crs/MachineConfigSctp.yaml
      patches:
        - metadata:
            labels:
              machineconfiguration.openshift.io/role: master
- name: mc-chronyd-policy
  manifests:
    - path: source-crs/MachineConfigDisableChronyd.yaml
      patches:
        - metadata:
            labels:
              machineconfiguration.openshift.io/role: master
- name: sriov-operconfig-policy
  manifests:
    - path: source-crs/SriovOperatorConfig.yaml
      patches:
        - spec:
            disableDrain: true
- name: mc-accelerated-policy
  manifests:
    - path: source-crs/MachineConfigAcceleratedStartup.yaml
      patches:
        - metadata:
            name: 04-accelerated-container-startup-master
            labels:
              machineconfiguration.openshift.io/role: master
- name: disable-network-diag-policy
  manifests:
    - path: source-crs/DisableSnoNetworkDiag.yaml
      patches:
        - metadata:
            labels:
              machineconfiguration.openshift.io/role: master
- name: ptp-config-policy
  manifests:
    - path: source-crs/PtpConfigSlave.yaml
      patches:
        - metadata:
            name: "du-ptp-slave"
          spec:
            recommend:
            - profile: "slave"
              priority: 4
              match:
                - nodeLabel: node-role.kubernetes.io/master
            profile:
            - name: "slave"
              interface: "ens5f0"
              ptp4lOpts: "-2 -s --summary_interval -4"
              phc2sysOpts: "-a -r -n 24"
              ptp4lConf: |
                [global]
                #
                # Default Data Set
                #
                twoStepFlag 1
                slaveOnly 0
                priority1 128
                priority2 128
                domainNumber 24
                #utc_offset 37
                clockClass 248
                clockAccuracy 0xFE
                offsetScaledLogVariance 0xFFFF
                free_running 0
                freq_est_interval 1
                dscp_event 0
                dscp_general 0
                dataset_comparison ieee1588
                G.8275.defaultDS.localPriority 128
                #
                # Port Data Set
                #
                logAnnounceInterval -3
                logSyncInterval -4
                logMinDelayReqInterval -4
                logMinPdelayReqInterval -4
                announceReceiptTimeout 3
                syncReceiptTimeout 0
                delayAsymmetry 0
                fault_reset_interval 4
                neighborPropDelayThresh 20000000
                masterOnly 0
                G.8275.portDS.localPriority 128
                #
                # Run time options
                #
                assume_two_step 0
                logging_level 6
                path_trace_enabled 0
                follow_up_info 0
                hybrid_e2e 0
                inhibit_multicast_service 0
                net_sync_monitor 0
                tc_spanning_tree 0
                tx_timestamp_timeout 1
                unicast_listen 0
                unicast_master_table 0
                unicast_req_duration 3600
                use_syslog 1
                verbose 0
                summary_interval 0
                kernel_leap 1
                check_fup_sync 0
                #
                # Servo Options
                #
                pi_proportional_const 0.0
                pi_integral_const 0.0
                pi_proportional_scale 0.0
                pi_proportional_exponent -0.3
                pi_proportional_norm_max 0.7
                pi_integral_scale 0.0
                pi_integral_exponent 0.4
                pi_integral_norm_max 0.3
                step_threshold 0.0
                first_step_threshold 0.00002
                max_frequency 900000000
                clock_servo pi
                sanity_freq_limit 200000000
                ntpshm_segment 0
                #
                # Transport options
                #
                transportSpecific 0x0
                ptp_dst_mac 01:1B:19:00:00:00
                p2p_dst_mac 01:80:C2:00:00:0E
                udp_ttl 1
                udp6_scope 0x0E
                uds_address /var/run/ptp4l
                #
                # Default interface options
                #
                clock_type OC
                network_transport UDPv4
                delay_mechanism E2E
                time_stamping hardware
                tsproc_mode filter
                delay_filter moving_median
                delay_filter_length 10
                egressLatency 0
                ingressLatency 0
                boundary_clock_jbod 0
                #
                # Clock description
                #
                productDescription ;;
                revisionData ;;
                manufacturerIdentity 00:00:00
                userDescription ;
                timeSource 0xA0

